server:
  shutdown: graceful
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sf_database_name
    username: james
    password: sf_password
  jpa:
    hibernate:
      ddl-auto: create
#        hbm2ddl:
#          auto: create
    generate-ddl: true
    show-sql: true

jasypt:
  encryptor:
    bean: jasyptEncryptor
    property:
      prefix: ENC(
      suffix: )
    password: testPassword

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE