server:
  shutdown: graceful
  port: 8088

spring:
  datasource:
    url: ENC(MDmerrpXqrramVtKSXCjQECf/ZkoW7T2jdkMtzgbKuoKfBhQMBsCECaYdF/ljJTdTV4GO5sTYoB/sKfXgFToJ0lKztuBj+Gv/4D/8X038hbF8vZTpObs6KalEkhRWVRN)
    username: ENC(XB9aBQBLeQzkCinzj9TCJw9R6dbgQjJcPqCgha7h6THdEI4xWUyewIjXWLllRd6Z)
    password: ENC(7+M8fdG5rAhphAhFJMtOMhNMbYFKz6hisHnA5QE8r+XQ3j/JWArJXsRq+u3iYIhs9pctPgYKWCXNOr9R2fISwg==)
    driver-class-name: org.postgresql.Driver