server:
  shutdown: graceful
  port: 8088

spring:
  jpa:
    hibernate:
      ddl-auto: update
#        hbm2ddl:
#          auto: create
    generate-ddl: true
    show-sql: true

jasypt:
  encryptor:
    bean: jasyptEncryptor
    property:
      prefix: ENC(
      suffix: )

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE