server:
  shutdown: graceful
  port: 8080

spring:
  jpa:
    open-in-view: false
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true

jasypt:
  encryptor:
    bean: jasyptEncryptor
    property:
      prefix: ENC(
      suffix: )